version: "3.8"
services:
  # Mysql database container
  db:
    image: mysql
    container_name: db_cosmic
    hostname: db_cosmic
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: user
      MYSQL_DATABASE: db
      MYSQL_USER: user
      MYSQL_PASSWORD: user
    ports:
      - 3306:3306
    networks:
      - cosmic

  # Symfony apache project container
  www:
    build: docker/php
    container_name: api_cosmic
    hostname: api_cosmic
    ports:
      - 8740:80
    volumes:
      - ./docker/php/vhosts:/etc/apache2/sites-enabled
      - ./:/var/www/charlotte
    restart: always
    networks:
      - cosmic
    depends_on:
      - db

networks:
  cosmic:
    external:
      name: cosmic