version: "3.8"
services:
  # Mysql database container
  db:
    image: mysql
    container_name: db_symfony
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: user
      MYSQL_DATABASE: db
      MYSQL_USER: user
      MYSQL_PASSWORD: user
    ports:
      - 3306:3306
    networks:
      - tutorial

  # Symfony apache project container
  www:
    build: docker/php
    container_name: api_symfony
    ports:
      - 8740:80
    volumes:
      - ./docker/php/vhosts:/etc/apache2/sites-enabled
      - ./:/var/www/charlotte
    restart: always
    networks:
      - tutorial
    depends_on:
      - db

networks:
  tutorial:

volumes:
  db-data:
